name: Nodejs build
on: push
jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: dockerhub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: docker build and push
        uses: docker/build-push-action@v5
        with:
#          context: .
#          file: Dockerfile
          push: true
          tags: cslgduke/node-app:${{ github.sha }}

